import Head from 'next/head'
import Image from 'next/image'
import Theatre from '../views/Theatre'
import Worlds from '../views/Worlds'
import Paradox from '../views/Paradox'
import Characters from '../views/Characters'
import Team from '../views/Team'
import Roadmap from '../views/Roadmap'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Paradox Realm</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Theatre />
        <Worlds />
        <Paradox />
        <Roadmap />
        <Characters />
        <Team />
      </main>
    </div>
  )
}
