import Head from 'next/head'
import Image from 'next/image'
import Theatre from '../components/views/Theatre'
import Worlds from '../components/views/Worlds'
import Paradox from '../components/views/Paradox'
import Characters from '../components/views/Characters'
import Team from '../components/views/Team'
import Roadmap from '../components/views/Roadmap'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Paradox Realm</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Theatre />
        {/* <Worlds />
        <Paradox />
        <Roadmap />
        <Characters />
        <Team /> */}
      </main>
    </div>
  )
}
